### ISSUE TITLE
spike 相关的设备模拟工作

### ISSUE THREAD

**Issue by Phantom1003** [isrc-cas/PLCT-Weekly#141]
想确认一下周报中提到的块设备、网卡设备在 [仓库](https://github.com/isrc-cas/plct-spike) 的哪个分支 ？

**Comment by liweiwei90** [comment]
- 块设备的分支和snapshot功能在一起（snapshot-develop分支，https://github.com/isrc-cas/plct-spike/tree/snapshot-develop）

- 网卡设备代码仓库中间出了点问题，现在尚未开源出来，后续整理过后会提供出来
